### ISSUE TITLE
Chromeless causes problems

### ISSUE THREAD

**Issue by delasource** [NeutroniumCore/Neutronium.SPA.Demo#1]
I am having trouble using the Chromeless Features. In detail: In MainWindow.xaml where there is 
```
    <i:Interaction.Behaviors>
        <WPF:Chromeless />
    </i:Interaction.Behaviors>
```
i either get "Interaction.Behaviours not found" or "Chromeless can not be added to a BehaviourCollection" (type mismatch i guess) using either the `Expression.Blend.Sdk` or the `Expression.Blend.Sdk3` *nuget package.*

So to clear it, i'd like to ask, which version of System.Windows.Interactivity.dll are you using, and where do i get it?!

**Comment by David-Desmaisons** [comment]
Got Expression.Blend.Sdk throught installation of the blend SDK. https://www.microsoft.com/en-us/download/details.aspx?id=10801
I guess a better solution would be to use nuget packages. I will take a look and try update Neutronium project to use Blend SDK.

**Comment by David-Desmaisons** [comment]
@genyx , please check if installing the SDK (link above) solve the issue. Thanks.

**Comment by David-Desmaisons** [comment]
I am now using nuget package to not depend from blend sdk installation
