### ISSUE TITLE
Project Dependency Needs Update

### ISSUE THREAD

**Issue by BenDerPan** [NeutroniumCore/Neutronium.SPA.Demo#2]
I use vs2017, I tried to update the nuget packages(.net 4.6.1), but it's not compatible with new version of Neutronium libs.

the vs template also have the same problem, could you please update this demo with the new version libs?

**Comment by David-Desmaisons** [comment]
Hello, I am not sure what the problem is.
I just build the project locally and everything is fine.
I am not sure what nuget package you are referring to since the nuget are already updated to last version 1.3.1.
Could you detail the exact problem which is resulting to the error?

**Comment by BenDerPan** [comment]
sorry for that I did not write it clearly, you can reproduce it by the steps:
1. open nuget management
![image](https://user-images.githubusercontent.com/10903567/48457567-2dbef980-e7fe-11e8-84f5-96608389339e.png)

2.  the select update, and update all
![image](https://user-images.githubusercontent.com/10903567/48457690-89898280-e7fe-11e8-916b-b2e04e33cd6c.png)

### This may not be a really problem if we keep the old version of dependencies, but I think keep a newer major version compatible is much better for future.  :)

**Comment by David-Desmaisons** [comment]
I got you. Well if you update all package to the last ones, you will probably get breaking changes that need to fixed. That's what is happening here. Nothing unusal thought.
